=== svn2github/yes-cart-trunk/core/src/main/resources/xstream/import-descriptor-1.0.0.xsd
<!--
  ~ Copyright 2009 Igor Azarnyi, Denys Pavlov
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<!--
    Schema for all import descriptor files.

    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://www.yes-cart.org/xstream/import-descriptor-1.0.0.xsd"

    This namespace is not actually pointing to the URL for schema, so you need to
    create an alias in your IDE that would point that namespace to this file.

    @author D.Pavlov
 -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="import-descriptor" type="ImportDescriptorType"/>

    <xs:complexType name="ImportDescriptorType">
        <xs:annotation>
            <xs:documentation>
                Defines the schema for how to represent an import descriptor.
                In general it maps and entity type (by interface) to columns in
                tuples source (e.g. a CSV file).

                File descriptor section specifies file specific configurations and columns
                define the actual mapping for columns to entity type.

                select-sql defines query that is to be used to look up existing object (HSQL)
                insert-sql defines a native insert query to improve performance (NATIVE SQL)
                It is possible to write several statement and they should be separated by ";\n"
                (semi-colon followed by a new line)

                Syntax for queries follows either native SQL or HSQL with parameters
                specified as column names in curly brackets.
                e.g.
                    HSQL: select c from CategoryEntity c where c.guid = {guid}
                    SQL : insert into TCATEGORY (GUID) values ('{guid}')
                Note the difference that '' are necessary for native SQL but not for HSQL.
                There are special placeholders in addition to {column} placeholders:
                1. {masterObjectId} PK of the maste object
                2. {masterObject} master instance (for use with HSQL)
                3. {GUID} auto generated guid (for use with native SQL inserts)

            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="entity-type" type="xs:string" minOccurs="1"/>
            <xs:element name="import-file-descriptor" type="ImportFileDescriptorType" minOccurs="1"/>
            <xs:element name="select-sql" type="xs:string" minOccurs="1"/>
            <xs:element name="insert-sql" type="xs:string" minOccurs="0"/>
            <xs:element name="import-columns" type="ImportColumnsType" minOccurs="1"/>
        </xs:sequence>

    </xs:complexType>


    <xs:complexType name="ImportFileDescriptorType">
        <xs:annotation>
            <xs:documentation>
                Filemask is important aspect of the import descriptor since when uploading a zip file
                with many sources this mask will filter out only relevant files applicable to this
                import descriptor.
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="file-encoding" type="xs:string"/>
            <xs:element name="file-name-mask" type="xs:string"/>
            <xs:element name="ignore-first-line" type="xs:boolean"/>
            <xs:element name="column-delimiter" type="xs:string"/>
            <xs:element name="text-qualifier" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ImportColumnsType">
        <xs:sequence>
            <xs:element name="column-descriptor" minOccurs="1" maxOccurs="unbounded" type="ImportColumnType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ImportColumnType">
        <xs:annotation>
            <xs:documentation>
                Column index defines the index of a column in a tuple that is represented by
                a property with name (i.e. name element) on the entity type. Say mapping
                column-index = 0 and name = code means that 0th column in import tuple is mapped
                to code property on the entity to be imported.

                If language is defined the values will be attempted to be inserted as a i18n.
                The language specified must be exactly the same configuration as Locale used by
                YeS (Yes Shop).

                Field type defined what type of field this is and will define the import strategy
                for that field (e.g. FK_FIELD would fetch a parent entity using lookup-query).
                For FK field entity-type must be specified to auto generate parent dependencies.

                Value regex allows to extract data from the column to allow more control over what
                gets imported into entity. By default group 1 is selected as the value but it is possible
                to define custom group by specifying regex group element.

                Constants just mean that some columns will be prepopulated with values. This is
                useful in some case, as for example setting default online properties for products.

                Lookup query is used to check is the entity exists for normal fields or to retrieve
                parent entities for FK fields. The query syntax follows HSQL (Hibernate) syntax
            </xs:documentation>
        </xs:annotation>
        <xs:sequence>
            <xs:element name="column-index" type="xs:int"/>
            <xs:element name="field-type">
                <xs:annotation>
                    <xs:documentation>
                        This constraint corresponds to org.yes.cart.bulkimport.model.FieldTypeEnum.
                    </xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="FIELD"/>
                        <xs:enumeration value="FK_FIELD"/>
                        <xs:enumeration value="SLAVE_INLINE_FIELD"/>
                        <xs:enumeration value="SLAVE_TUPLE_FIELD"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="data-type" minOccurs="0">
                <xs:annotation>
                    <xs:documentation>
                        This constraint corresponds to org.yes.cart.bulkimport.model.DataTypeEnum.
                    </xs:documentation>
                </xs:annotation>
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="STRING"/>
                        <xs:enumeration value="BOOLEAN"/>
                        <xs:enumeration value="LONG"/>
                        <xs:enumeration value="INT"/>
                        <xs:enumeration value="DECIMAL"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element name="entity-type" type="xs:string" minOccurs="0"/>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="language" type="xs:string" minOccurs="0"/>
            <xs:element name="value-regex" type="xs:string" minOccurs="0"/>
            <xs:element name="value-regex-group" type="xs:string" minOccurs="0"/>
            <xs:element name="value-constant" type="xs:string" minOccurs="0"/>
            <xs:element name="lookup-query" type="xs:string" minOccurs="0"/>
            <xs:element name="use-master-object" type="xs:boolean" minOccurs="0"/>
            <xs:element name="import-descriptor" type="ImportDescriptorType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== svn2github/yes-cart-trunk/manager/server/src/main/webapp/WEB-INF/import-descriptor/productnames.xml
<!--
  ~ Copyright 2009 Igor Azarnyi, Denys Pavlov
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<import-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="http://www.yes-cart.org/xstream/import-descriptor-1.0.0.xsd">

    <entity-type>org.yes.cart.domain.entity.Product</entity-type>

    <import-directory></import-directory>

    <import-file-descriptor>
        <file-encoding>UTF-8</file-encoding>
        <file-name-mask>productnames(.*).csv(.*)</file-name-mask>
        <ignore-first-line>true</ignore-first-line>
        <column-delimiter>;</column-delimiter>
        <text-qualifier>&quot;</text-qualifier>
    </import-file-descriptor>

    <select-sql>select p from ProductEntity p where p.guid = {guid}</select-sql>

    <import-columns>

        <!-- Primary key -->
        <column-descriptor>
            <column-index>0</column-index>
            <field-type>FIELD</field-type>
            <name>guid</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <!-- SKU code -->
        <column-descriptor>
            <column-index>1</column-index>
            <field-type>FIELD</field-type>
            <name>code</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <!-- brand -->
        <column-descriptor>
            <column-index>3</column-index>
            <field-type>FK_FIELD</field-type>
            <entity-type>org.yes.cart.domain.entity.Brand</entity-type>
            <name>brand</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
            <lookup-query>select b from BrandEntity b where b.name = {brand}</lookup-query>
        </column-descriptor>

        <!-- product type -->
        <column-descriptor>
            <column-index>4</column-index>
            <field-type>FK_FIELD</field-type>
            <entity-type>org.yes.cart.domain.entity.ProductType</entity-type>
            <name>producttype</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
            <lookup-query>select pt from ProductTypeEntity pt where pt.name = {producttype}</lookup-query>
        </column-descriptor>

        <!--  Productname -->
        <column-descriptor>
            <column-index>6</column-index>
            <field-type>FIELD</field-type>
            <name>name</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <!-- TODO: add localisable -->

        <!-- availability type -->
        <column-descriptor>
            <column-index>-1</column-index>
            <field-type>FIELD</field-type>
            <name>availability</name>
            <value-constant>1</value-constant>
        </column-descriptor>

        <!-- Description -->
        <column-descriptor>
            <column-index>9</column-index>
            <field-type>FIELD</field-type>
            <name>description</name>
            <value-regex>(.{0,4000})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <!-- TODO: add localisable -->

        <!--featured-->
        <column-descriptor>
            <column-index>-1</column-index>
            <field-type>FIELD</field-type>
            <data-type>BOOLEAN</data-type>
            <name>featured</name>
            <value-constant>false</value-constant>
        </column-descriptor>

    </import-columns>
</import-descriptor>

=== svn2github/yes-cart-trunk/manager/server/src/main/webapp/WEB-INF/import-descriptor/shopcurrencies-demo.xml
<!--
  ~ Copyright 2009 Igor Azarnyi, Denys Pavlov
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<import-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="http://www.yes-cart.org/xstream/import-descriptor-1.0.0.xsd">

    <entity-type>org.yes.cart.domain.entity.AttrValueShop</entity-type>

    <import-file-descriptor>
        <file-encoding>UTF-8</file-encoding>
        <file-name-mask>shopcurrencies(.*).csv(.*)</file-name-mask>
        <ignore-first-line>true</ignore-first-line>
        <column-delimiter>;</column-delimiter>
        <text-qualifier>&quot;</text-qualifier>
    </import-file-descriptor>

    <select-sql>select c from AttrValueEntityShop c where c.shop.code = 'SHOP10' and c.attribute.code = 'CURRENCY'</select-sql>

    <import-columns>

        <column-descriptor>
            <column-index>0</column-index>
            <field-type>FIELD</field-type>
            <name>val</name>
        </column-descriptor>

        <column-descriptor>
            <column-index>-1</column-index>
            <field-type>FK_FIELD</field-type>
            <name>shop</name>
            <lookup-query>select s from ShopEntity s where s.code = 'SHOP10'</lookup-query>
        </column-descriptor>

        <column-descriptor>
            <column-index>-1</column-index>
            <field-type>FK_FIELD</field-type>
            <name>attribute</name>
            <lookup-query>select a from AttributeEntity a where a.code = 'CURRENCY'</lookup-query>
        </column-descriptor>

    </import-columns>
</import-descriptor>

=== svn2github/yes-cart-trunk/manager/server/src/main/webapp/WEB-INF/import-descriptor/carrierslanames.xml
<!--
  ~ Copyright 2009 Igor Azarnyi, Denys Pavlov
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<import-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="http://www.yes-cart.org/xstream/import-descriptor-1.0.0.xsd">

    <entity-type>org.yes.cart.domain.entity.CarrierSla</entity-type>

    <import-directory></import-directory>

    <import-file-descriptor>
        <file-encoding>UTF-8</file-encoding>
        <file-name-mask>carrierslanames(.*).csv(.*)</file-name-mask>
        <ignore-first-line>true</ignore-first-line>
        <column-delimiter>;</column-delimiter>
        <text-qualifier>&quot;</text-qualifier>
    </import-file-descriptor>

    <select-sql>select c from CarrierSlaEntity c where c.name = {name} and c.carrier.name = {carrier}</select-sql>

    <import-columns>

        <column-descriptor>
            <column-index>0</column-index>
            <field-type>FIELD</field-type>
            <name>name</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-index>1</column-index>
            <field-type>FIELD</field-type>
            <name>displayName</name>
            <language>en</language>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-index>2</column-index>
            <field-type>FIELD</field-type>
            <name>displayName</name>
            <language>ru</language>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-index>3</column-index>
            <field-type>FIELD</field-type>
            <name>description</name>
            <value-regex>(.{0,4000})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-index>6</column-index>
            <field-type>FIELD</field-type>
            <data-type>DECIMAL</data-type>
            <name>price</name>
        </column-descriptor>

        <column-descriptor>
            <column-index>-1</column-index>
            <field-type>FIELD</field-type>
            <data-type>DECIMAL</data-type>
            <name>percent</name>
            <value-constant>0.00</value-constant>
        </column-descriptor>

        <column-descriptor>
            <column-index>7</column-index>
            <field-type>FIELD</field-type>
            <name>currency</name>
        </column-descriptor>

        <column-descriptor>
            <column-index>8</column-index>
            <field-type>FK_FIELD</field-type>
            <entity-type>org.yes.cart.domain.entity.Carrier</entity-type>
            <name>carrier</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
            <lookup-query>select c from CarrierEntity c where c.name = {carrier}</lookup-query>
        </column-descriptor>

        <column-descriptor>
            <column-index>9</column-index>
            <field-type>FIELD</field-type>
            <name>slaType</name>
            <value-regex>(.{1,1})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-index>10</column-index>
            <field-type>FIELD</field-type>
            <data-type>INT</data-type>
            <name>maxDays</name>
        </column-descriptor>

    </import-columns>
</import-descriptor>

=== svn2github/yes-cart-trunk/core/src/test/resources/import/productypeattributeviewgroupnames.xml
<!--
  ~ Copyright 2009 Igor Azarnyi, Denys Pavlov
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<import-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="http://www.yes-cart.org/xstream/import-descriptor-1.0.0.xsd">

    <entity-type>org.yes.cart.domain.entity.ProdTypeAttributeViewGroup</entity-type>

    <import-file-descriptor>
        <file-encoding>UTF-8</file-encoding>
        <file-name-mask>productypeattributeviewgroupnames.csv</file-name-mask>
        <ignore-first-line>true</ignore-first-line>
        <column-delimiter>;</column-delimiter>
        <text-qualifier>&quot;</text-qualifier>
    </import-file-descriptor>

    <select-sql>select p from ProdTypeAttributeViewGroupEntity p where p.guid = {guid}</select-sql>

    <import-columns>

        <!-- Product type -->
        <column-descriptor>
            <column-index>0</column-index>
            <field-type>FK_FIELD</field-type>
            <entity-type>org.yes.cart.domain.entity.ProductType</entity-type>
            <name>producttype</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
            <lookup-query>select p from ProductTypeEntity p where p.name = {producttype}</lookup-query>
        </column-descriptor>

        <!-- primary key -->
        <column-descriptor>
            <column-index>1</column-index>
            <field-type>FIELD</field-type>
            <name>guid</name>
            <value-regex>(.{0,36})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>


        <!-- attr view group -->
        <column-descriptor>
            <column-index>2</column-index>
            <field-type>FIELD</field-type>
            <name>name</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-index>3</column-index>
            <field-type>FIELD</field-type>
            <name>displayName</name>
            <language>en</language>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <column-descriptor>
            <column-index>4</column-index>
            <field-type>FIELD</field-type>
            <name>displayName</name>
            <language>ru</language>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <!-- attributes code list -->
        <column-descriptor>
            <column-index>5</column-index>
            <field-type>FIELD</field-type>
            <name>attrCodeList</name>
            <value-regex>(.{0,4000})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

    </import-columns>
</import-descriptor>

=== svn2github/yes-cart-trunk/core/src/test/resources/import/skuprice.xml
<!--
  ~ Copyright 2009 Igor Azarnyi, Denys Pavlov
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<import-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="http://www.yes-cart.org/xstream/import-descriptor-1.0.0.xsd">

    <entity-type>org.yes.cart.domain.entity.SkuPrice</entity-type>

    <import-directory>src/test/resources/import</import-directory>

    <import-file-descriptor>
        <file-encoding>UTF-8</file-encoding>
        <file-name-mask>productentity.csv</file-name-mask>
        <ignore-first-line>true</ignore-first-line>
        <column-delimiter>;</column-delimiter>
        <text-qualifier>&quot;</text-qualifier>
    </import-file-descriptor>

    <import-columns>

        <column-descriptor>
            <column-index>5</column-index>
            <field-type>FIELD</field-type>
            <name/>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
            <lookup-query>
                select p from SkuPriceEntity p
                where p.sku.code = ?1
                and p.shop.code = 'SHOIP1'
                and p.currency = 'USD'
                and p.quantity = 1
            </lookup-query> <!-- at this moment i see only one price tier -->
        </column-descriptor>

        <column-descriptor>
            <column-index>5</column-index>
            <field-type>FK_FIELD</field-type>
            <name>sku</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
            <lookup-query>select p from ProductSkuEntity p where p.code = ?1</lookup-query>
        </column-descriptor>


        <column-descriptor>
            <column-index>-1</column-index>
            <field-type>FK_FIELD</field-type>
            <name>shop</name>
            <lookup-query>select a from ShopEntity a where a.code = 'SHOIP1'</lookup-query>
        </column-descriptor>

        <column-descriptor>
            <column-index>7</column-index>
            <field-type>FIELD</field-type>
            <name>regularPrice</name>
        </column-descriptor>


        <column-descriptor>
            <column-index>-1</column-index>
            <field-type>FIELD</field-type>
            <name>quantity</name>
            <value-constant>1</value-constant>
        </column-descriptor>

        <column-descriptor>
            <column-index>-1</column-index>
            <field-type>FIELD</field-type>
            <name>currency</name>
            <value-constant>USD</value-constant>
        </column-descriptor>

    </import-columns>
</import-descriptor>

=== svn2github/yes-cart-trunk/core/src/test/resources/import/shopcategory.xml
<!--
  ~ Copyright 2009 Igor Azarnyi, Denys Pavlov
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<import-descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                   xsi:noNamespaceSchemaLocation="http://www.yes-cart.org/xstream/import-descriptor-1.0.0.xsd">

    <entity-type>org.yes.cart.domain.entity.ShopCategory</entity-type>

    <import-directory>src/test/resources/import</import-directory>

    <import-file-descriptor>
        <file-encoding>UTF-8</file-encoding>
        <file-name-mask>categorynames.csv</file-name-mask>
        <ignore-first-line>true</ignore-first-line>
        <column-delimiter>;</column-delimiter>
        <text-qualifier>&quot;</text-qualifier>
    </import-file-descriptor>

    <select-sql>select p from ShopCategoryEntity p where p.category.guid = {category} and p.shop.code = 'SHOIP1'</select-sql>

    <import-columns>

        <column-descriptor>
            <column-index>-1</column-index>
            <field-type>FIELD</field-type>
            <name>guid</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
        </column-descriptor>

        <!-- Category -->
        <column-descriptor>
            <column-index>1</column-index>
            <field-type>FK_FIELD</field-type>
            <entity-type>org.yes.cart.domain.entity.Category</entity-type>
            <name>category</name>
            <value-regex>(.{0,255})(.*)</value-regex>
            <value-regex-group>1</value-regex-group>
            <lookup-query>select c from CategoryEntity c where c.guid = {category}</lookup-query>
        </column-descriptor>

        <!-- Shop -->
        <column-descriptor>
            <column-index>-1</column-index>
            <field-type>FK_FIELD</field-type>
            <entity-type>org.yes.cart.domain.entity.Shop</entity-type>
            <name>shop</name>
            <lookup-query>select a from ShopEntity a where a.code = 'SHOIP1'</lookup-query>
        </column-descriptor>


    </import-columns>
</import-descriptor>
