=== svn2github/yes-cart-trunk/core/src/main/resources/xstream/product-type-range-list-1.0.0.xsd
<!--
  ~ Copyright 2009 Igor Azarnyi, Denys Pavlov
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<!--
    Schema for all import descriptor files.

    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="http://www.yes-cart.org/xstream/product-type-range-list-1.0.0.xsd"

    This namespace is not actually pointing to the URL for schema, so you need to
    create an alias in your IDE that would point that namespace to this file.

    @author D.Pavlov
 -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="range-list" type="RangeListType"/>

    <xs:complexType name="RangeListType">
        <xs:sequence>
            <xs:element name="ranges">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="range" type="RangeType" minOccurs="0" maxOccurs="unbounded"/>
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="RangeType">
        <xs:sequence>
            <xs:element name="from" type="xs:string"/>
            <xs:element name="to" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== svn2github/yes-cart-trunk/persistence/src/test/resources/weight_filtering_example.xml
<!--
  ~ Copyright 2009 Igor Azarnyi, Denys Pavlov
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~        http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<range-list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="http://www.yes-cart.org/xstream/product-type-range-list-1.0.0.xsd">
    <ranges>
        <range>
            <from>0.10</from>
            <to>1.00</to>
        </range>
        <range>
            <from>1.00</from>
            <to>2.00</to>
        </range>
        <range>
            <from>2.00</from>
            <to>3.00</to>
        </range>
        <range>
            <from>3.00</from>
            <to>4.00</to>
        </range>
    </ranges>
</range-list>
